### PR TITLE
Test automatic versioning using frau-ci

### PR DESCRIPTION
**Pull request by AllanKerr**

### CODE REVIEW

**Comment by m6jones** [comment]
Does this give us the ability to indicate which version we are updating? 
In the merge comments I can do `[increment [path|minor|major]]` and if I don't add that then the version doesn't auto increment?

**Comment by AllanKerr** [comment]
> Does this give us the ability to indicate which version we are updating?
> In the merge comments I can do `[increment [path|minor|major]]` and if I don't add that then the version doesn't auto increment?

It automatically defaults to bumping the minor version if nothing is specified, if you specify [increment patch] or [increment major] then it will increment those instead.

**Comment by m6jones** [comment]
Is there a don't bump option?

**Comment by AllanKerr** [comment]
> Is there a don't bump option?

Sort of, you can use `[skip ci]`. If you want your change to run through CI then the version must be bumped.

**Pull request merged**
